on:
  schedule:
    - crone: '*/2 * * * *' // schedule every 2 minutes
  push:
    

jobs:
  hello_world:
      runs-on: ubuntu-latest
      steps:
        - name: echo currunt time
          run: |
            echo "Hello, World!"
            echo "Current date and time: $(date)" 